# Generated by Django 5.0.4 on 2024-05-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.BinaryField(max_length=30)),
                ('last_name', models.BinaryField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
